language: python

python:
  - 2.7
  - 3.4
  - 3.5

install:
  - pip install grako
  - pip install coveralls
  - python setup.py install

script:
  - python setup.py nosetests

after_success:
  - coveralls
